### ISSUE TITLE
Unable to Build with readme instructions

### ISSUE THREAD

**Issue by tylermauthe** [kris-nova/oddit#12]
I had to run `go get github.com/kris-nova/oddit` to put the libs into the right place for the build to run correctly.

I'm really new to Go, so I don't really know how to fix. If you'd like, I could try to find some time and fix this. Let me know!

**Comment by kris-nova** [comment]
Thanks for the heads up @tylermauthe - I added new install directions, and made a few changes to the code. This should now be fixed and you can run

`go get github.com/kris-nova/oddit` for the command line tool :)

**Comment by tylermauthe** [comment]
Awesome! I'll give it a try on a fresh install :)
